# Generated by Django 5.1.5 on 2025-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datapoint",
            name="added",
        ),
        migrations.RemoveField(
            model_name="datapoint",
            name="impact",
        ),
        migrations.RemoveField(
            model_name="datapoint",
            name="published",
        ),
        migrations.AddField(
            model_name="datapoint",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="swot",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
