# Generated by Django 5.1.5 on 2025-02-06 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "visualization",
            "0002_remove_datapoint_added_remove_datapoint_impact_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="datapoint",
            old_name="year",
            new_name="start_year",
        ),
    ]
