# Generated by Django 5.1.5 on 2025-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualization", "0003_rename_year_datapoint_start_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datapoint",
            name="published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
