# Generated by Django 5.1.5 on 2025-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualization", "0004_datapoint_added_datapoint_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datapoint",
            name="source",
            field=models.TextField(blank=True, null=True),
        ),
    ]
