# Generated by Django 5.1.5 on 2025-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visualization", "0005_alter_datapoint_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datapoint",
            name="city",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="country",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="pestle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="region",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="sector",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="swot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="topic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datapoint",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
